SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `carriers` (
  `id` int UNSIGNED NOT NULL,
  `country_id` int UNSIGNED NOT NULL,
  `name` varchar(100) NOT NULL,
  `gateway` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `carriers` (`id`, `country_id`, `name`, `gateway`) VALUES
(1, 107, 'AirCel', 'number@aircel.co.in'),
(2, 107, 'Airtel', 'number@airtelap.com'),
(3, 107, 'Airtel', 'number@airtelkk.com'),
(4, 235, 'AirFire Mobile', 'number@sms.airfiremobile.com'),
(5, 235, 'Aio Wireless', 'number@mms.aiowireless.net'),
(6, 235, 'Alaska Communications', 'number@msg.acsalaska.com'),
(7, 39, 'Aliant Canada', 'number@sms.wirefree.informe.ca'),
(8, 235, 'Alltel (Allied Wireless)', 'number@mms.alltelwireless.com'),
(9, 235, 'Verizon Wireless', 'number@vzwpix.com'),
(10, 235, 'Ameritech', 'number@paging.acswireless.com'),
(11, 107, 'Andhra Pradesh AirTel', 'number@airtelap.com'),
(12, 107, 'Andhra Pradesh Idea', 'number@ideacellular.net'),
(13, 235, 'Assurance Wireless', 'number@vmobl.com'),
(14, 235, 'AT&T Mobility', 'number@mms.att.net'),
(15, 235, 'AT&T Enterprise Paging', 'number@page.att.net'),
(16, 193, 'Beeline', 'number@sms.beemail.ru'),
(17, 39, 'Bell Mobility', 'number@txt.bell.ca'),
(18, 235, 'BellSouth', 'number@bellsouth.cl'),
(19, 235, 'Bluegrass Cellular', 'number@mms.myblueworks.com'),
(20, 246, 'Bluesky Communications', 'number@psms.bluesky.as'),
(21, 235, 'Boost mobile', 'number@myboostmobile.com'),
(22, 77, 'Bouygues Telecom', 'number@mms.bouyguestelecom.fr'),
(23, 44, 'Box Internet Services', 'number@mms.boxis.net'),
(24, 77, 'SFR', 'number@sfr.fr'),
(25, 235, 'CellCom', 'number@cellcom.quiktxt.com'),
(26, 235, 'Cellular South', 'number@csouth1.com'),
(27, 235, 'Centennial Wireless', 'number@cwemail.com'),
(28, 235, 'Chariton Valley Wireless', 'number@sms.cvalley.net'),
(29, 235, 'Chat Mobility', 'number@mail.msgsender.com'),
(30, 107, 'Chennai Skycell / Airtel', 'number@airtelchennai.com'),
(31, 107, 'Chennai RPG Cellular', 'number@rpgmail.net'),
(32, 49, 'China Mobile', 'number@139.com'),
(33, 235, 'Cincinnati Bell', 'number@mms.gocbw.com'),
(34, 32, 'Claro', 'number@clarotorpedo.com.br'),
(35, 167, 'Claro', 'number@ideasclaro-ca.com'),
(36, 184, 'Claro', 'number@vtexto.com'),
(37, 235, 'Cleartalk', 'number@sms.cleartalk.us'),
(38, 50, 'Claro', 'number@iclaro.com.co'),
(39, 235, 'Cricket', 'number@mms.mycricket.com'),
(40, 235, 'C Spire Wireless', 'number@cspire1.com'),
(41, 97, 'Accessyou', 'number@messaging.accessyou.com'),
(42, 97, 'CSL', 'number@mgw.mmsc1.hkcsl.com'),
(43, 11, 'CTI Móvil (Now Claro)', 'number@sms.ctimovil.com.ar'),
(44, 107, 'Delhi Airtel', 'number@airtelmail.com'),
(45, 62, 'Digicel', 'number@digitextdm.com'),
(46, 235, 'DTC', 'number@sms.advantagecell.net'),
(47, 59, 'E-Plus', 'number@smsmail.eplus.de'),
(48, 235, 'Edge Wireless', 'number@sms.edgewireless.com'),
(49, 235, 'Element Mobile', 'number@SMS.elementmobile.net'),
(50, 156, 'Emtel', 'number@emtelworld.net'),
(51, 0, 'Esendex', 'number@echoemail.net'),
(52, 70, 'Esendex', 'number@esendex.net'),
(53, 39, 'Fido', 'number@sms.fido.ca'),
(54, 13, 'Firmensms', 'number@subdomain.firmensms.at'),
(55, 0, 'Freebie SMS', 'number@smssturen.com'),
(56, 235, 'General Communications Inc.', 'number@mobile.gci.net'),
(57, 0, 'Globalstar', 'number@msg.globalstarusa.com'),
(58, 23, 'Globul', 'number@sms.globul.bg'),
(59, 107, 'Goa Airtel', 'number@airtelmail.com'),
(60, 107, 'Goa Idea Cellular', 'number@ideacellular.net'),
(61, 235, 'Golden State Cellular', 'number@gscsms.com'),
(62, 235, 'Greatcall', 'number@vtxt.com'),
(63, 107, 'Gujarat Idea Cellular', 'number@ideacellular.net'),
(64, 107, 'Gujarat Airtel', 'number@airtelmail.com'),
(65, 107, 'Gujarat Celforce / Fascel', 'number@celforce.com'),
(66, 96, 'Guyana T&T', 'number@sms.cellinkgy.com'),
(67, 107, 'Haryana Airtel', 'number@airtelmail.com'),
(68, 107, 'Haryana Escotel', 'number@escotelmobile.com'),
(69, 235, 'Hawaiian Telcom', 'number@hawaii.sprintpcs.com'),
(70, 79, 'HSL Mobile', 'number@sms.haysystems.com'),
(71, 124, 'Helio', 'number@myhelio.com'),
(72, 107, 'Himachai Pradesh Airtel', 'number@airtelmail.com'),
(73, 51, 'ICE', 'number@sms.ice.cr'),
(74, 235, 'I-wireless(T-Mobile)', 'number.iws@iwspcs.net'),
(75, 235, 'I-wireless(Sprint PCS)', 'number@iwirelesshometext.com'),
(76, 235, 'Kajeet', 'number@mobile.kajeet.net'),
(77, 107, 'Karnataka Airtel', 'number@airtelkk.com'),
(78, 107, 'Kerala Airtel', 'number@airtelkerala.com'),
(79, 107, 'Kerala Escotel', 'number@escotelmobile.com'),
(80, 107, 'Kolkata Airtel', 'number@airtelkol.com'),
(81, 39, 'Koodo Mobile', 'number@msg.telus.com'),
(82, 235, 'LongLines', 'number@text.longlines.com'),
(83, 39, 'Lynx Mobility', 'number@sms.lynxmobility.com'),
(84, 200, 'M1', 'number@m1.com.sg'),
(85, 107, 'Madhya Pradesh Airtel', 'number@airtelmail.com'),
(86, 107, 'Maharashtra Airtel', 'number@airtelmail.com'),
(87, 107, 'Maharashtra Idea', 'number@ideacellular.net'),
(88, 175, 'Más Móvil', 'number@cwmovil.com'),
(89, 79, 'Mediaburst', 'number@sms.mediaburst.co.uk'),
(90, 235, 'MetroPCS', 'number@mymetropcs.com'),
(91, 23, 'Mobiltel', 'number@sms.mtel.net'),
(92, 132, 'Mobitel', 'number@sms.mobitel.lk'),
(93, 11, 'Movistar', 'number@sms.movistar.net.ar'),
(94, 50, 'Movistar', 'number@movistar.com.co'),
(95, 70, 'Movistar', '0number@movistar.net'),
(96, 0, 'Movistar', 'number@movimensaje.com.ar'),
(97, 236, 'Movistar', 'number@sms.movistar.com.uy'),
(98, 250, 'MTN', 'number@sms.co.za'),
(99, 39, 'MTS Mobility', 'number@text.mtsmobility.com'),
(100, 107, 'Mumbai Airtel', 'number@airtelmail.com'),
(101, 79, 'My-Cool-SMS', 'number@my-cool-sms.com'),
(102, 235, 'Nextech', 'number@sms.ntwls.net'),
(103, 159, 'Nextel', 'number@msgnextel.com.mx'),
(104, 11, 'Nextel', 'TwoWay.11number@nextel.net.ar'),
(105, 59, 'O2', 'number@o2online.de'),
(106, 111, 'OgVodafone', 'number@sms.is'),
(107, 168, 'Orange', 'number@sms.orange.nl'),
(108, 79, 'Orange', 'number@orange.net'),
(109, 235, 'Page Plus Cellular (Verizon)', 'number@vzwpix.com'),
(110, 235, 'Pioneer Cellular', 'nine-digit-number@zsend.com'),
(111, 11, 'Personal', 'number@alertas.personal.com.ar'),
(112, 181, 'Plus', 'number@text.plusgsm.pl'),
(113, 235, 'Pocket Wireless', 'number@sms.pocket.com'),
(114, 39, 'PC Telecom', 'number@mobiletxt.ca'),
(115, 181, 'Polkomtel', 'number@text.plusgsm.pl'),
(116, 235, 'Qwest Wireless', 'number@qwestmp.com'),
(117, 235, 'Red Pocket Mobile', 'number@mms.att.net'),
(118, 0, 'Rogers Wireless', 'number@mms.rogers.com'),
(119, 39, 'SaskTel', 'number@pcs.sasktelmobility.com'),
(120, 169, 'Sendega', 'number@sendega.com'),
(121, 15, 'Setar Mobile email (Aruba)', 'number@mas.aw'),
(122, 111, 'Síminn', 'number@box.is'),
(123, 235, 'Simple Mobile', 'number@smtext.com'),
(124, 14, 'SMS Broadcast', 'number@send.smsbroadcast.com.au'),
(125, 14, 'SMS Central', 'number@sms.smscentral.com.au'),
(126, 14, 'SMSPUP', 'number@smspup.com'),
(127, 235, 'Southernlinc', 'number@page.southernlinc.com'),
(128, 235, 'South Central Communications', 'number@rinasms.com'),
(129, 105, 'Spikko', 'number@SpikkoSMS.com'),
(130, 235, 'Sprint', 'number@pm.sprint.com'),
(131, 235, 'Straight Talk', 'number@mms.att.net');


ALTER TABLE `carriers`
  ADD PRIMARY KEY (`id`),
  ADD KEY `country_id` (`country_id`);


ALTER TABLE `carriers`
  MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=142;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
