SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `countries` (
  `id` int UNSIGNED NOT NULL,
  `code` char(2) DEFAULT NULL,
  `name` varchar(45) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `countries` (`id`, `code`, `name`) VALUES
(1, 'AD', 'Andorra'),
(2, 'AE', 'United Arab Emirates'),
(3, 'AF', 'Afghanistan'),
(4, 'AG', 'Antigua and Barbuda'),
(5, 'AI', 'Anguilla'),
(6, 'AL', 'Albania'),
(7, 'AM', 'Armenia'),
(8, 'AN', 'Netherlands Antilles'),
(9, 'AO', 'Angola'),
(10, 'AQ', 'Antarctica'),
(11, 'AR', 'Argentina'),
(12, 'AS', 'American Samoa'),
(13, 'AT', 'Austria'),
(14, 'AU', 'Australia'),
(15, 'AW', 'Aruba'),
(16, 'AX', 'Aland Islands'),
(17, 'AZ', 'Azerbaijan'),
(18, 'BA', 'Bosnia and Herzegovina'),
(19, 'BB', 'Barbados'),
(20, 'BD', 'Bangladesh'),
(21, 'BE', 'Belgium'),
(22, 'BF', 'Burkina Faso'),
(23, 'BG', 'Bulgaria'),
(24, 'BH', 'Bahrain'),
(25, 'BI', 'Burundi'),
(26, 'BJ', 'Benin'),
(27, 'BL', 'Saint Barthélemy'),
(28, 'BM', 'Bermuda'),
(29, 'BN', 'Brunei'),
(30, 'BO', 'Bolivia'),
(31, 'BQ', 'Bonaire, Saint Eustatius and Saba '),
(32, 'BR', 'Brazil'),
(33, 'BS', 'Bahamas'),
(34, 'BT', 'Bhutan'),
(35, 'BV', 'Bouvet Island'),
(36, 'BW', 'Botswana'),
(37, 'BY', 'Belarus'),
(38, 'BZ', 'Belize'),
(39, 'CA', 'Canada'),
(40, 'CC', 'Cocos Islands'),
(41, 'CD', 'Democratic Republic of the Congo'),
(42, 'CF', 'Central African Republic'),
(43, 'CG', 'Republic of the Congo'),
(44, 'CH', 'Switzerland'),
(45, 'CI', 'Ivory Coast'),
(46, 'CK', 'Cook Islands'),
(47, 'CL', 'Chile'),
(48, 'CM', 'Cameroon'),
(49, 'CN', 'China'),
(50, 'CO', 'Colombia'),
(51, 'CR', 'Costa Rica'),
(52, 'CS', 'Serbia and Montenegro'),
(53, 'CU', 'Cuba'),
(54, 'CV', 'Cape Verde'),
(55, 'CW', 'Curaçao'),
(56, 'CX', 'Christmas Island'),
(57, 'CY', 'Cyprus'),
(58, 'CZ', 'Czech Republic'),
(59, 'DE', 'Germany'),
(60, 'DJ', 'Djibouti'),
(61, 'DK', 'Denmark'),
(62, 'DM', 'Dominica'),
(63, 'DO', 'Dominican Republic'),
(64, 'DZ', 'Algeria'),
(65, 'EC', 'Ecuador'),
(66, 'EE', 'Estonia'),
(67, 'EG', 'Egypt'),
(68, 'EH', 'Western Sahara'),
(69, 'ER', 'Eritrea'),
(70, 'ES', 'Spain'),
(71, 'ET', 'Ethiopia'),
(72, 'FI', 'Finland'),
(73, 'FJ', 'Fiji'),
(74, 'FK', 'Falkland Islands'),
(75, 'FM', 'Micronesia'),
(76, 'FO', 'Faroe Islands'),
(77, 'FR', 'France'),
(78, 'GA', 'Gabon'),
(79, 'GB', 'United Kingdom'),
(80, 'GD', 'Grenada'),
(81, 'GE', 'Georgia'),
(82, 'GF', 'French Guiana'),
(83, 'GG', 'Guernsey'),
(84, 'GH', 'Ghana'),
(85, 'GI', 'Gibraltar'),
(86, 'GL', 'Greenland'),
(87, 'GM', 'Gambia'),
(88, 'GN', 'Guinea'),
(89, 'GP', 'Guadeloupe'),
(90, 'GQ', 'Equatorial Guinea'),
(91, 'GR', 'Greece'),
(92, 'GS', 'South Georgia and the South Sandwich Islands'),
(93, 'GT', 'Guatemala'),
(94, 'GU', 'Guam'),
(95, 'GW', 'Guinea-Bissau'),
(96, 'GY', 'Guyana'),
(97, 'HK', 'Hong Kong'),
(98, 'HM', 'Heard Island and McDonald Islands'),
(99, 'HN', 'Honduras'),
(100, 'HR', 'Croatia'),
(101, 'HT', 'Haiti'),
(102, 'HU', 'Hungary'),
(103, 'ID', 'Indonesia'),
(104, 'IE', 'Ireland'),
(105, 'IL', 'Israel'),
(106, 'IM', 'Isle of Man'),
(107, 'IN', 'India'),
(108, 'IO', 'British Indian Ocean Territory'),
(109, 'IQ', 'Iraq'),
(110, 'IR', 'Iran'),
(111, 'IS', 'Iceland'),
(112, 'IT', 'Italy'),
(113, 'JE', 'Jersey'),
(114, 'JM', 'Jamaica'),
(115, 'JO', 'Jordan'),
(116, 'JP', 'Japan'),
(117, 'KE', 'Kenya'),
(118, 'KG', 'Kyrgyzstan'),
(119, 'KH', 'Cambodia'),
(120, 'KI', 'Kiribati'),
(121, 'KM', 'Comoros'),
(122, 'KN', 'Saint Kitts and Nevis'),
(123, 'KP', 'North Korea'),
(124, 'KR', 'South Korea'),
(125, 'KW', 'Kuwait'),
(126, 'KY', 'Cayman Islands'),
(127, 'KZ', 'Kazakhstan'),
(128, 'LA', 'Laos'),
(129, 'LB', 'Lebanon'),
(130, 'LC', 'Saint Lucia'),
(131, 'LI', 'Liechtenstein'),
(132, 'LK', 'Sri Lanka'),
(133, 'LR', 'Liberia'),
(134, 'LS', 'Lesotho'),
(135, 'LT', 'Lithuania'),
(136, 'LU', 'Luxembourg'),
(137, 'LV', 'Latvia'),
(138, 'LY', 'Libya'),
(139, 'MA', 'Morocco'),
(140, 'MC', 'Monaco'),
(141, 'MD', 'Moldova'),
(142, 'ME', 'Montenegro'),
(143, 'MF', 'Saint Martin'),
(144, 'MG', 'Madagascar'),
(145, 'MH', 'Marshall Islands'),
(146, 'MK', 'Macedonia'),
(147, 'ML', 'Mali'),
(148, 'MM', 'Myanmar'),
(149, 'MN', 'Mongolia'),
(150, 'MO', 'Macao'),
(151, 'MP', 'Northern Mariana Islands'),
(152, 'MQ', 'Martinique'),
(153, 'MR', 'Mauritania'),
(154, 'MS', 'Montserrat'),
(155, 'MT', 'Malta'),
(156, 'MU', 'Mauritius'),
(157, 'MV', 'Maldives'),
(158, 'MW', 'Malawi'),
(159, 'MX', 'Mexico'),
(160, 'MY', 'Malaysia'),
(161, 'MZ', 'Mozambique'),
(162, 'NA', 'Namibia'),
(163, 'NC', 'New Caledonia'),
(164, 'NE', 'Niger'),
(165, 'NF', 'Norfolk Island'),
(166, 'NG', 'Nigeria'),
(167, 'NI', 'Nicaragua'),
(168, 'NL', 'Netherlands'),
(169, 'NO', 'Norway'),
(170, 'NP', 'Nepal'),
(171, 'NR', 'Nauru'),
(172, 'NU', 'Niue'),
(173, 'NZ', 'New Zealand'),
(174, 'OM', 'Oman'),
(175, 'PA', 'Panama'),
(176, 'PE', 'Peru'),
(177, 'PF', 'French Polynesia'),
(178, 'PG', 'Papua New Guinea'),
(179, 'PH', 'Philippines'),
(180, 'PK', 'Pakistan'),
(181, 'PL', 'Poland'),
(182, 'PM', 'Saint Pierre and Miquelon'),
(183, 'PN', 'Pitcairn'),
(184, 'PR', 'Puerto Rico'),
(185, 'PS', 'Palestinian Territory'),
(186, 'PT', 'Portugal'),
(187, 'PW', 'Palau'),
(188, 'PY', 'Paraguay'),
(189, 'QA', 'Qatar'),
(190, 'RE', 'Reunion'),
(191, 'RO', 'Romania'),
(192, 'RS', 'Serbia'),
(193, 'RU', 'Russia'),
(194, 'RW', 'Rwanda'),
(195, 'SA', 'Saudi Arabia'),
(196, 'SB', 'Solomon Islands'),
(197, 'SC', 'Seychelles'),
(198, 'SD', 'Sudan'),
(199, 'SE', 'Sweden'),
(200, 'SG', 'Singapore'),
(201, 'SH', 'Saint Helena'),
(202, 'SI', 'Slovenia'),
(203, 'SJ', 'Svalbard and Jan Mayen'),
(204, 'SK', 'Slovakia'),
(205, 'SL', 'Sierra Leone'),
(206, 'SM', 'San Marino'),
(207, 'SN', 'Senegal'),
(208, 'SO', 'Somalia'),
(209, 'SR', 'Suriname'),
(210, 'SS', 'South Sudan'),
(211, 'ST', 'Sao Tome and Principe'),
(212, 'SV', 'El Salvador'),
(213, 'SX', 'Sint Maarten'),
(214, 'SY', 'Syria'),
(215, 'SZ', 'Swaziland'),
(216, 'TC', 'Turks and Caicos Islands'),
(217, 'TD', 'Chad'),
(218, 'TF', 'French Southern Territories'),
(219, 'TG', 'Togo'),
(220, 'TH', 'Thailand'),
(221, 'TJ', 'Tajikistan'),
(222, 'TK', 'Tokelau'),
(223, 'TL', 'East Timor'),
(224, 'TM', 'Turkmenistan'),
(225, 'TN', 'Tunisia'),
(226, 'TO', 'Tonga'),
(227, 'TR', 'Turkey'),
(228, 'TT', 'Trinidad and Tobago'),
(229, 'TV', 'Tuvalu'),
(230, 'TW', 'Taiwan'),
(231, 'TZ', 'Tanzania'),
(232, 'UA', 'Ukraine'),
(233, 'UG', 'Uganda'),
(234, 'UM', 'United States Minor Outlying Islands'),
(235, 'US', 'United States'),
(236, 'UY', 'Uruguay'),
(237, 'UZ', 'Uzbekistan'),
(238, 'VA', 'Vatican'),
(239, 'VC', 'Saint Vincent and the Grenadines'),
(240, 'VE', 'Venezuela'),
(241, 'VG', 'British Virgin Islands'),
(242, 'VI', 'U.S. Virgin Islands'),
(243, 'VN', 'Vietnam'),
(244, 'VU', 'Vanuatu'),
(245, 'WF', 'Wallis and Futuna'),
(246, 'WS', 'Samoa'),
(247, 'XK', 'Kosovo'),
(248, 'YE', 'Yemen'),
(249, 'YT', 'Mayotte'),
(250, 'ZA', 'South Africa'),
(251, 'ZM', 'Zambia'),
(252, 'ZW', 'Zimbabwe');


ALTER TABLE `countries`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_country_code` (`code`);


ALTER TABLE `countries`
  MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=262;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
